from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ModuleHelp(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, module_name=None, help_text=None):  # noqa: E501
        """ModuleHelp - a model defined in OpenAPI

        :param module_name: The module_name of this ModuleHelp.  # noqa: E501
        :type module_name: str
        :param help_text: The help_text of this ModuleHelp.  # noqa: E501
        :type help_text: str
        """
        self.openapi_types = {
            'module_name': str,
            'help_text': str
        }

        self.attribute_map = {
            'module_name': 'moduleName',
            'help_text': 'helpText'
        }

        self._module_name = module_name
        self._help_text = help_text

    @classmethod
    def from_dict(cls, dikt) -> 'ModuleHelp':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ModuleHelp of this ModuleHelp.  # noqa: E501
        :rtype: ModuleHelp
        """
        return util.deserialize_model(dikt, cls)

    @property
    def module_name(self) -> str:
        """Gets the module_name of this ModuleHelp.

        Normalized module/class name the help text was generated for  # noqa: E501

        :return: The module_name of this ModuleHelp.
        :rtype: str
        """
        return self._module_name

    @module_name.setter
    def module_name(self, module_name: str):
        """Sets the module_name of this ModuleHelp.

        Normalized module/class name the help text was generated for  # noqa: E501

        :param module_name: The module_name of this ModuleHelp.
        :type module_name: str
        """
        if module_name is None:
            raise ValueError("Invalid value for `module_name`, must not be `None`")  # noqa: E501

        self._module_name = module_name

    @property
    def help_text(self) -> str:
        """Gets the help_text of this ModuleHelp.

        Captured output from Python's help() function  # noqa: E501

        :return: The help_text of this ModuleHelp.
        :rtype: str
        """
        return self._help_text

    @help_text.setter
    def help_text(self, help_text: str):
        """Sets the help_text of this ModuleHelp.

        Captured output from Python's help() function  # noqa: E501

        :param help_text: The help_text of this ModuleHelp.
        :type help_text: str
        """
        if help_text is None:
            raise ValueError("Invalid value for `help_text`, must not be `None`")  # noqa: E501

        self._help_text = help_text
