from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.td_node_error import TdNodeError
from openapi_server import util

from openapi_server.models.td_node_error import TdNodeError  # noqa: E501

class TdNodeErrorReport(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, node_path=None, node_name=None, op_type=None, error_count=None, has_errors=None, errors=None):  # noqa: E501
        """TdNodeErrorReport - a model defined in OpenAPI

        :param node_path: The node_path of this TdNodeErrorReport.  # noqa: E501
        :type node_path: str
        :param node_name: The node_name of this TdNodeErrorReport.  # noqa: E501
        :type node_name: str
        :param op_type: The op_type of this TdNodeErrorReport.  # noqa: E501
        :type op_type: str
        :param error_count: The error_count of this TdNodeErrorReport.  # noqa: E501
        :type error_count: int
        :param has_errors: The has_errors of this TdNodeErrorReport.  # noqa: E501
        :type has_errors: bool
        :param errors: The errors of this TdNodeErrorReport.  # noqa: E501
        :type errors: List[TdNodeError]
        """
        self.openapi_types = {
            'node_path': str,
            'node_name': str,
            'op_type': str,
            'error_count': int,
            'has_errors': bool,
            'errors': List[TdNodeError]
        }

        self.attribute_map = {
            'node_path': 'nodePath',
            'node_name': 'nodeName',
            'op_type': 'opType',
            'error_count': 'errorCount',
            'has_errors': 'hasErrors',
            'errors': 'errors'
        }

        self._node_path = node_path
        self._node_name = node_name
        self._op_type = op_type
        self._error_count = error_count
        self._has_errors = has_errors
        self._errors = errors

    @classmethod
    def from_dict(cls, dikt) -> 'TdNodeErrorReport':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TdNodeErrorReport of this TdNodeErrorReport.  # noqa: E501
        :rtype: TdNodeErrorReport
        """
        return util.deserialize_model(dikt, cls)

    @property
    def node_path(self) -> str:
        """Gets the node_path of this TdNodeErrorReport.

        Path that was inspected for errors  # noqa: E501

        :return: The node_path of this TdNodeErrorReport.
        :rtype: str
        """
        return self._node_path

    @node_path.setter
    def node_path(self, node_path: str):
        """Sets the node_path of this TdNodeErrorReport.

        Path that was inspected for errors  # noqa: E501

        :param node_path: The node_path of this TdNodeErrorReport.
        :type node_path: str
        """
        if node_path is None:
            raise ValueError("Invalid value for `node_path`, must not be `None`")  # noqa: E501

        self._node_path = node_path

    @property
    def node_name(self) -> str:
        """Gets the node_name of this TdNodeErrorReport.

        Name of the inspected node  # noqa: E501

        :return: The node_name of this TdNodeErrorReport.
        :rtype: str
        """
        return self._node_name

    @node_name.setter
    def node_name(self, node_name: str):
        """Sets the node_name of this TdNodeErrorReport.

        Name of the inspected node  # noqa: E501

        :param node_name: The node_name of this TdNodeErrorReport.
        :type node_name: str
        """
        if node_name is None:
            raise ValueError("Invalid value for `node_name`, must not be `None`")  # noqa: E501

        self._node_name = node_name

    @property
    def op_type(self) -> str:
        """Gets the op_type of this TdNodeErrorReport.

        Operator type of the inspected node  # noqa: E501

        :return: The op_type of this TdNodeErrorReport.
        :rtype: str
        """
        return self._op_type

    @op_type.setter
    def op_type(self, op_type: str):
        """Sets the op_type of this TdNodeErrorReport.

        Operator type of the inspected node  # noqa: E501

        :param op_type: The op_type of this TdNodeErrorReport.
        :type op_type: str
        """
        if op_type is None:
            raise ValueError("Invalid value for `op_type`, must not be `None`")  # noqa: E501

        self._op_type = op_type

    @property
    def error_count(self) -> int:
        """Gets the error_count of this TdNodeErrorReport.

        Number of errors that were discovered  # noqa: E501

        :return: The error_count of this TdNodeErrorReport.
        :rtype: int
        """
        return self._error_count

    @error_count.setter
    def error_count(self, error_count: int):
        """Sets the error_count of this TdNodeErrorReport.

        Number of errors that were discovered  # noqa: E501

        :param error_count: The error_count of this TdNodeErrorReport.
        :type error_count: int
        """
        if error_count is None:
            raise ValueError("Invalid value for `error_count`, must not be `None`")  # noqa: E501

        self._error_count = error_count

    @property
    def has_errors(self) -> bool:
        """Gets the has_errors of this TdNodeErrorReport.

        Convenience flag indicating if any errors were found  # noqa: E501

        :return: The has_errors of this TdNodeErrorReport.
        :rtype: bool
        """
        return self._has_errors

    @has_errors.setter
    def has_errors(self, has_errors: bool):
        """Sets the has_errors of this TdNodeErrorReport.

        Convenience flag indicating if any errors were found  # noqa: E501

        :param has_errors: The has_errors of this TdNodeErrorReport.
        :type has_errors: bool
        """
        if has_errors is None:
            raise ValueError("Invalid value for `has_errors`, must not be `None`")  # noqa: E501

        self._has_errors = has_errors

    @property
    def errors(self) -> List[TdNodeError]:
        """Gets the errors of this TdNodeErrorReport.

        Collection of raw node errors  # noqa: E501

        :return: The errors of this TdNodeErrorReport.
        :rtype: List[TdNodeError]
        """
        return self._errors

    @errors.setter
    def errors(self, errors: List[TdNodeError]):
        """Sets the errors of this TdNodeErrorReport.

        Collection of raw node errors  # noqa: E501

        :param errors: The errors of this TdNodeErrorReport.
        :type errors: List[TdNodeError]
        """
        if errors is None:
            raise ValueError("Invalid value for `errors`, must not be `None`")  # noqa: E501

        self._errors = errors
