from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class TdNodeError(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, node_path=None, node_name=None, op_type=None, message=None):  # noqa: E501
        """TdNodeError - a model defined in OpenAPI

        :param node_path: The node_path of this TdNodeError.  # noqa: E501
        :type node_path: str
        :param node_name: The node_name of this TdNodeError.  # noqa: E501
        :type node_name: str
        :param op_type: The op_type of this TdNodeError.  # noqa: E501
        :type op_type: str
        :param message: The message of this TdNodeError.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'node_path': str,
            'node_name': str,
            'op_type': str,
            'message': str
        }

        self.attribute_map = {
            'node_path': 'nodePath',
            'node_name': 'nodeName',
            'op_type': 'opType',
            'message': 'message'
        }

        self._node_path = node_path
        self._node_name = node_name
        self._op_type = op_type
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'TdNodeError':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TdNodeError of this TdNodeError.  # noqa: E501
        :rtype: TdNodeError
        """
        return util.deserialize_model(dikt, cls)

    @property
    def node_path(self) -> str:
        """Gets the node_path of this TdNodeError.

        Absolute operator path that reported the error  # noqa: E501

        :return: The node_path of this TdNodeError.
        :rtype: str
        """
        return self._node_path

    @node_path.setter
    def node_path(self, node_path: str):
        """Sets the node_path of this TdNodeError.

        Absolute operator path that reported the error  # noqa: E501

        :param node_path: The node_path of this TdNodeError.
        :type node_path: str
        """
        if node_path is None:
            raise ValueError("Invalid value for `node_path`, must not be `None`")  # noqa: E501

        self._node_path = node_path

    @property
    def node_name(self) -> str:
        """Gets the node_name of this TdNodeError.

        Name of the operator  # noqa: E501

        :return: The node_name of this TdNodeError.
        :rtype: str
        """
        return self._node_name

    @node_name.setter
    def node_name(self, node_name: str):
        """Sets the node_name of this TdNodeError.

        Name of the operator  # noqa: E501

        :param node_name: The node_name of this TdNodeError.
        :type node_name: str
        """
        if node_name is None:
            raise ValueError("Invalid value for `node_name`, must not be `None`")  # noqa: E501

        self._node_name = node_name

    @property
    def op_type(self) -> str:
        """Gets the op_type of this TdNodeError.

        TouchDesigner operator type  # noqa: E501

        :return: The op_type of this TdNodeError.
        :rtype: str
        """
        return self._op_type

    @op_type.setter
    def op_type(self, op_type: str):
        """Sets the op_type of this TdNodeError.

        TouchDesigner operator type  # noqa: E501

        :param op_type: The op_type of this TdNodeError.
        :type op_type: str
        """
        if op_type is None:
            raise ValueError("Invalid value for `op_type`, must not be `None`")  # noqa: E501

        self._op_type = op_type

    @property
    def message(self) -> str:
        """Gets the message of this TdNodeError.

        Error message reported by TouchDesigner  # noqa: E501

        :return: The message of this TdNodeError.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this TdNodeError.

        Error message reported by TouchDesigner  # noqa: E501

        :param message: The message of this TdNodeError.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message
